### ISSUE TITLE
Token from one session is valid in another session?

### ISSUE THREAD

**Issue by appdrake** [expressjs/csurf#101]
I'm a security tester.  The dev team I work with used this module to add CSRF protection to their single page Node app.  The X-CSRF-Token is created in the header and used on all the POSTs in the page.  On a new browser tab, the single page app renders with a new X-CSRF-Token as expected.  All seems in working order.
 
I use one of the many proxies available to mess with the input on the client side.  I took the X-CSRF-Token from the 1st tab and used it in a POST on the 2nd tab and it worked.  Seems to me it shouldn't have worked if the token housekeeping on the server is accurate.  Next, in an entirely new browser window and different user session, I reused the same X-CSRF-Token token, and again, it worked.  Now I really think something is wrong.  Is the implementation of how the dev team is using it wrong?  Has anyone else tried this?  Thanks.

**Comment by dougwilson** [comment]
> Is the implementation of how the dev team is using it wrong? Has anyone else tried this?

It probably is. There is nothing I can say besides"it should not do that" without understanding how the dev team actually used this module to understand what is going wrong.

**Comment by dougwilson** [comment]
So, in order for us to proceed with taking a look, please provide all the following information:

1. Version of Node.js being used.
2. Version of this module being used.
3. Complete source code needed for me to run and create an app that has this issue.
4. Complete step by step instructions for how to reproduce the issue. Be sure to include a description of how to know that the issue is occurring and what you expect the app to be doing at that stage.

Thank you!

**Comment by appdrake** [comment]
Sorry for the delay in responding about this issue.  The dev team has re-implemented how they were using the API and it now seems cool.  Thanks for your responses.  I will close this issue.
