### ISSUE TITLE
Throw changes in 1.9.0 are breaking changes

### ISSUE THREAD

**Issue by scottnonnenberg** [expressjs/csurf#103]
The changes to throw behavior in [1.9.0](https://github.com/expressjs/csurf/blob/master/HISTORY.md#190--2016-05-27) are breaking changes. I've needed to make code changes to preserve intended behavior.

It probably should have been a 2.0.0. Maybe consider releasing a 1.9.1 reverting these changes along with a 2.0.0?

Let me also say that I really appreciate the changes. I needed to do weird things before, now it's a whole lot more natural. :0)

**Comment by dougwilson** [comment]
With 1.9.0 being out for over four months now, even a reversion is a breaking change. There is no good solution here... If you brought it up even at least in the first month, maybe, but unfortunately I'm not going to revert, the most I can do is apologize.

Going back to throw is likely to be even more breaking, because that is over four months of time for people to use this module in a way where throwing will be an uncaught exception.

**Comment by scottnonnenberg** [comment]
Fair enough; thanks for the response. Sadly, there'll be a trickle of people like me over time, running into this as they also do their (too-infrequent) dependency updates...

**Comment by dougwilson** [comment]
Yea, I mean, there are a few issues here with the reversion:

1. This module is downloaded from npm ~ 1 million times per month. That means that in the four months, there has been about 4 million downloads, which excluding how many is the same version over and over, it's a fair bet there are quite a few new users.
2. There were no promises this module made that certain errors were thrown and certain ones were next(err). This means that if you were treating them differently, you probably looked in the source or figured it out, but were takin on the risk of using undocumented behavior.
3. Technically this was a bug fix. This module inherently promises to behave like a middleware, and using middleware that throws is very painful. It is expected that errors are next(err), not thrown, and throwing was unexpected. There is no technical difference between a bug fix and a breaking change, as every bug fix is a breaking change. The best I can do is try to hoist "big bug"s into minor releases instead of patch releases.

I hope this makes sense.
