### ISSUE TITLE
Question: cookie or session?

### ISSUE THREAD

**Issue by aseemk** [expressjs/csurf#108]
Hi there,

Great work on this library and Express/Connect in general. We at @FiftyThree have been using it for years and have appreciated the value it provides.

One question: aside from ease of use (e.g. for small, new apps that don't have a session store at first), is there any advantage to placing the CSRF token in the existing session (`cookie: false`, which is the default) vs. in a new cookie (`cookie: true`)?

Does this answer change if the session store we're using is itself a (signed) cookie? (Via the [`cookie-session`](https://github.com/expressjs/cookie-session) middleware.)

Even if there aren't any major differences in theory, are there any potentially significant ones in practice, especially around security?

Thank you!

**Comment by tomek121** [comment]
Additional question from me. Which one method is much more safer? Storing the token in the session (server) or in cookie (client)?

**Comment by caco0516** [comment]
You have to stored token in session because is where you gonna compare token posted from request against token from session. Don't forget to use another session store option for production.

**Comment by dougwilson** [comment]
Both (stored on the server with `cookie: false` and stored on the client with `cookie: true`, or using a session module that stores the session's contents in the client) have their pros and cons, but as far as the raw CSRF protection goes, they are pretty much equivalent from the security point of view. The attack vector CSRF protects against is a user browsers to a malicious web site in their own browser and makes a request to your site that tries to perform an action. The CSRF protection works by requiring a piece of knowledge that they both do not know (since third-party sites cannot read the contents of your site) and isn't automatically submitted by the web browser with the request (which cookies are): the token in the form itself.

If the secret is stored on the server or in the client in a cookie doesn't make a difference to CSRF protection, since the way the server-side session is identified is by the cookie anyway, so if the third-party can read cookies, the protection will break down in either method, though it is slightly harder if you use server-side secret storage.

I hope that helps!

**Comment by aseemk** [comment]
It does help. Thank you @dougwilson!

**Comment by josecolella** [comment]
@dougwilson Thank you for the response.

**Comment by caco0516** [comment]
> Additional question from me. Which one method is much more safer? Storing the token in the session (server) or in cookie (client)?

Is safer to stored tokens in sessions and reference them with cookies , if cookie is compromised nothing happens because real token is hidden from attacker.
