### ISSUE TITLE
Cookie expiry can't be set dynamically

### ISSUE THREAD

**Issue by jamesmccann** [expressjs/csurf#119]
When setting the expiry for a cookie it's common to want to set a "duration" or TTL for the cookie and we can add that to the current time to get an expiry date, e.g. the express documentation on [res.cookie](http://expressjs.com/en/4x/api.html#res.cookie) shows the following example:

```
res.cookie('rememberme', '1', { expires: new Date(Date.now() + 900000), httpOnly: true });
```

Unfortunately calling csurf as the express app is booted with a similar config only allows for the expiry to be set at the time of call, e.g.:

```js
var cookieParser = require('cookie-parser')
var csrf = require('csurf')
var bodyParser = require('body-parser')
var express = require('express')

// setup route middlewares - cookie expires 24hrs from the time this call is made
var csrfProtection = csrf({ cookie: { expires: new Date(Date.now() + 24 * 60 * 60 * 1000) } })
var parseForm = bodyParser.urlencoded({ extended: false })

// create express app
var app = express()

// parse cookies
// we need this because "cookie" is true in csrfProtection
app.use(cookieParser())

app.get('/form', csrfProtection, function (req, res) {
  // pass the csrfToken to the view
  res.render('send', { csrfToken: req.csrfToken() })
})

app.post('/process', parseForm, csrfProtection, function (req, res) {
  res.send('data is being processed')
})
```

So the expiry for these cookies is going to be 24hrs from the time the app was started.

Is there a way around this or is it a limitation right now? Should it be possible to pass a function to the cookie property to allow this to be dynamic?

**Comment by dougwilson** [comment]
So a few things:

1. Ideally you want to use the session to store the secret instead of the cookie if you are using sessions. It keeps your management together in a single mechanism.
2. You really don't want to set `expires` by calculating the date manually; if you set `maxAge` instead to the life you want the cookie, that will give you the same thing you are trying to achieve without locking to a specific date / time, which is your issue.
3. But no matter what you'll run into a limitation of the cookie part of this module: it only ever sets the cookie once, so you'll end up with a new secret every 24 hours in your example. If you want the module to extend the timeout, some one will need to implement that feature.

**Comment by jamesmccann** [comment]
@dougwilson cheers for the feedback.

Looks like maxAge would indeed help here, sorry I must have overlooked that in the express docs! But your first point is also valid we'll look at rolling our csrf into our session.

Cheers for the quick answer!
