### ISSUE TITLE
Synchronous code used in the module

### ISSUE THREAD

**Issue by gsikorski** [expressjs/csurf#123]
The code uses synchronous code `secretSync` from `csrf` library. This blocks entire server. Better solution (JavaScript way) would be to use asynchronous `secret` function instead.

**Comment by dougwilson** [comment]
Hi @gsikorski yes, we use sync, but only because it's been proven to not block the entire server. Have you been seeing that happen? If so, can you provide an example reproduction case to demonstrate that it is (incorrectly) causing blocking?

**Comment by Jokero** [comment]
Then why https://github.com/pillarjs/csrf has both async and sync versions for secret generation? A bit confusing

**Comment by dougwilson** [comment]
Hi @Jokero yea, it basically just exposes both because at a time there was just async, then it was shown that the sync of random bytes does exactly the same thing, including it being very fast and no I/O. So then the sync methods were added but the async ones left around for compatibility with other modules who were also using the `csrf` module.
