### ISSUE TITLE
CSURF writes secret in every OPTIONS call. How to avoid this?

### ISSUE THREAD

**Issue by frederikhors** [expressjs/csurf#162]
I'm using this package in an express 4 server with CORS and `cookie-session` package (https://github.com/expressjs/cookie-session).

Today I noticed a `Set-Cookie` for the preflight OPTIONS calls.

After the OPTIONS preflight calls the cookie is still the old one, like the `Set-Cookie` in OPTIONS call Response Header does nothing.

This is strange, right?

I thinsk this package is writing `csrfSecret` in session also for OPTIONS calls.

In Readme you say:

> **ignoreMethods**
> An array of the methods for which CSRF token checking will disabled. Defaults to ['GET', 'HEAD', 'OPTIONS'].

I'm using the default, so I think it should ignore OPTIONS calls, but apparently this is not the case for the secret. **CSURF writes secret in every OPTIONS call session and `cookie-session` obviously writes new cookie every time.**

How to avoid this?

**Comment by dougwilson** [comment]
Strange, we should only be setting a secret if you called req.csrfToken and there is not a secret already in the request. Can you provide a reproduction case demonstrating the issue?

**Comment by frederikhors** [comment]
It's difficult because I don't know how to reproduce OPTIONS preflight calls on glitch. I need another domain, right?

**Comment by frederikhors** [comment]
But I can assure you the bug is there.

**Comment by dougwilson** [comment]
Yea, I get it. If you know where the bug is, can you please make a pull request with a fix? If you're looking for me to fix it, I need instructions on exactly how to reproduce it so I can also discover where the bug is and then have a way to validate the changes I make resolve the bug.

If you have another method for me to determine the issue and determine the fix, please let me know :)

**Comment by frederikhors** [comment]
@dougwilson you right. I will try to reproduce on glitch now. Thanks in advance.

**Comment by frederikhors** [comment]
I'm still working on a glitch reproduction but I think the problem is this:

Preflight OPTIONS calls doesn't have Cookie in requested header and so csurf doesn't recognize a session.csrfSecret coming from an inexhistent cookie in the header.

So it creates a new one for every OPTIONS call but the browser ignore it.

You can read more on this StackOverflow: https://stackoverflow.com/a/41760296/10088259

**Comment by dougwilson** [comment]
Well, I poked around and like I said above, this module doesn't even generate a secret to set unless your code somewhere is calling the req.csrfToken method (i.e. your code is saying it wanted a token so this module thus created a new secret for it).

**Comment by dougwilson** [comment]
Basically even if the request doesn't have a cookie (and thus no secret), csurf still never actually generates a secret until user code calls the req.csrfToken method indicating that a secret needs to be generated for that request.

**Comment by dougwilson** [comment]
Sorry, scratch a bunch of that above.

**Comment by dougwilson** [comment]
Can you share what your code looks like? Does it look like how our readme shows to use this module or something different? https://github.com/expressjs/csurf/blob/master/README.md#simple-express-example

Anything that can help so I'm not just poking around in the dark :) and can see the same thing you see.

**Comment by frederikhors** [comment]
Yeah. Simply default app with cookie-session.

**Comment by dougwilson** [comment]
So that's what I've been trying: the example in our docs I linked to but changed to use cookie session for secret storage. I haven't been able to reproduce it using that, so not sure what is different in code from your code or if my method is different from your method to reproduce.

Any clarity would be great. For now I'm going to move to a holding pattern until you can provide the exact code to reproduce and exact steps :+1: gotta runs errands.

**Comment by frederikhors** [comment]
@dougwilson I have a reproduction here: https://glitch.com/edit/#!/csurf-issues-162

If you use Postman with an OPTIONS call on this: https://csurf-issues-162.glitch.me/ you can see a Response Header with `Set-Cookie`.

I don't have any `req.csrfToken` as you can see: simply default code.

What I think is for OPTIONS calls csurf should not set anything (also because browsers ignore `Set-Cookie` on OPTIONS calls).

Here a screenshot:

![image](https://user-images.githubusercontent.com/41120635/45598406-d3f7aa00-b9db-11e8-9d5c-2e925c02f80c.png)

**Comment by dougwilson** [comment]
I will check out it when I get back home 👍 

> What I think is for OPTIONS calls csurf should not set anything (also because browsers ignore Set-Cookie on OPTIONS calls).

This is not correct -- you're thinking that CORS == OPTIONS. This is not correct. The OPTIONS method existed before CORS was even a thing. Yes, the CORS preflight requests _use_ the OPTIONS method, but the OPTIONS method is not _exclusive_ to CORS and you can make OPTIONS requests and the browsers will keep the cookies (it just don't keep the request if the OPTIONS call was _also_ a CORS preflight request).

I think the solution here will be more complex.

Also, I think you mislead me here: I asked if you were using the ode at https://github.com/expressjs/csurf/blob/master/README.md#simple-express-example and you said yes. But your code is not that. Why did you waste my time this morning with this misleading statement? I'll be looking forward to an explanation on this point before I continue.

**Comment by frederikhors** [comment]
Yes I forgot to use it on just one route, like in my project. But now I noticed something strange:

- If I use it like in your remixed glitch it works (doesn't Set-Cookie in Response header);
- if I use `cors()` in a single route it sends Set-Cookie in header: it's crazy!

`app.post('/', cors({ credentials: true }), (req, res) => res.send('POST endpoint'))`

Where am I wrong? Or something is broken in cors package?

I updated my code in https://glitch.com/edit/#!/csurf-issues-162

**Comment by dougwilson** [comment]
What route are you trying to protect with CSRF? The example I linked to shows how to use it on specific routes, which is the better way to use it (just like how you only want CORS on some routes).

Perhaps the issue is mixed use of some global middleware and non global middleware? Why not just either use everything global or go the route of declaring per route?

**Comment by frederikhors** [comment]
```js
var express = require('express');
const cors = require('cors')
const cookieSession = require('cookie-session')
const csrf = require('csurf')
const logger = require('morgan')
const router = express.Router()

var app = express();

app.use(logger('tiny'))

// app.use(cors({ credentials: true })) <-- OPTIONS calls with just this doesn't send `Set-Cookie` in response header.

app.use(cookieSession({
  name: 'session',
  keys: ['key1', 'key2'],
  maxAge: 24 * 60 * 60 * 1000
}))

app.use(csrf())

app.get('/', (req, res) => res.send('Ok, GET home page'))

// If I use it here OPTIONS calls on this have Set-Cookie in Response header
app.post('/', cors({ credentials: true }), (req, res) => res.send('POST endpoint'))

var listener = app.listen(process.env.PORT, function() {
  console.log('Your app is listening on port ' + listener.address().port);
});
```

**Comment by dougwilson** [comment]
Thanks for the code example! What route are you trying to protect with CSRF? The example I linked to shows how to use it on specific routes, which is the better way to use it (just like how you only want CORS on some routes).

Perhaps the issue is mixed use of some global middleware and non global middleware? Why not just either use everything global or go the route of declaring per route?

**Comment by frederikhors** [comment]
I wanna enable CORS just on one POST route. Not on every routes.

But now I have a doubt: for security concerns I have to use is on every route? Or just the one I use as public API endpoint?

**Comment by dougwilson** [comment]
I don't understand the security question, but even so I cannot answer it due to liability reasons. You'll want to consult a security expert (which I'm definitely not) to ensure you are implementing something securely.

**Comment by frederikhors** [comment]
Ok, @dougwilson.

I was confused but now it is more clear.

The problem is still there anyway: if I use `app.use(csrf())` globally and `cors()` locally (per route, like this: `app.post('/', cors({ credentials: true }), (req, res) => res.send('POST endpoint'))`), it `Set-Cookie` in response header.

This is the problem I think.

Reproduction here: https://glitch.com/edit/#!/csurf-issues-162

**Comment by dougwilson** [comment]
Right, that's what I'm wondering: What route are you trying to protect with CSRF? The example I linked to shows how to use it on specific routes, which is the better way to use it (just like how you only want CORS on some routes).
Perhaps the issue is mixed use of some global middleware and non global middleware? Why not just either use everything global or go the route of declaring per route?

**Comment by frederikhors** [comment]
@dougwilson I need to protect every route. CSRF protection is on every route, am I wrong? Or just I need it on CORS routes?

**Comment by dougwilson** [comment]
By default, the `csrf()` middleware will protect all requests excluding the ones where the method is in the `ignoreMethods` list. So yes, it would protect all routes when accessed with methods other than those. I think the issue is that `OPTIONS` is just another method like `PUT`, `PROPFIND`, `POST`, etc. so when you use it globally you're including those routes. The `cors()` module by default will respond to the preflight requests and stop the request from going further, basically automatically making other middleware below it "CORS aware". Any middleware you declare before `cors()` doesn't understand CORS, which is why you get the useless cookies on the preflight responses, as `cors()` isn't invoked before `csurf()` giving this module the knolwege that CORS is a thing.

**Comment by dougwilson** [comment]
Basically, the way your example is constructed is that you're declaring you want to include the CORS preflight requests under the CSRF umbrella by allowing this middleware to execute on those requests. Any request this middleware executes on will add the `req.csrfToken()` method to the requests so you can get a token. In order to do that, the secret needs to be created if not already there and stored.

**Comment by frederikhors** [comment]
Ok, @dougwilson thanks fr the great explanation.

But what you mean now is I can't use `csrf()` globally and `cors()` locally per-route?

This is not good I think.

I have to use `cors()` globally necessarily?

**Comment by dougwilson** [comment]
That's really just how it is currently made -- with Express middleware apply to the particular request that passes through it. Thus if you don't want something to apply to a given request, just don't pass the request through that middleware. That's basically what you're doing with the cors() middleware -- you didn't want that middleware to apply to _every_ request, so you moved it down to per-route.

You're then saying that you don't want csurf to apply to those preflight requests, but you're not moving the middleware such that those requests don't actually travel through the middleware. The cookies set are not harming anything, but if you want them not to set, then don't let this middleware execute on requests you don't want it to touch (i.e. those preflight requests).

**Comment by frederikhors** [comment]
The problem is still there @dougwilson. I really appreciate your hints but I can't move routes out from middleware flow, because of this:

- app.use(csrf())
  - route 1 (without cors)
  - route 2 (without cors)
  - route 3 (with cors)
  - route 4 (OPTIONS with cors and csrf)

How to move route 4 up in flow?

**Comment by dougwilson** [comment]
Rather than trying to use github issues as a chat, the Express system has multiple different ways to get help and support over chat systems that can have a real back and forth. You can find these listed at http://expressjs.com/en/resources/community.html

I am still out on errands and it's going to be some time before I can really provide adequate help.

**Comment by dougwilson** [comment]
> How to move route 4 up in flow?

Without knowing that those routes actually are, it's not possible to provide an answer, as ordering is different depending on what those routes actually are (the method, the path, what they do, etc).

**Comment by frederikhors** [comment]
I think I can put toue 4 (OPTIONS, with cors() without csrf()) up before `app.use(csrf())`.

It now works. What do you think? It is good?

**Comment by dougwilson** [comment]
If it works, then it seems like that would be good. There isn't much information for me to go on.

**Comment by frederikhors** [comment]
Thanks a lot. I really appreciated.
