### ISSUE TITLE
Using express-session cookies with csurf

### ISSUE THREAD

**Issue by klunghamer** [expressjs/csurf#171]
Hi, I'm using csurf with express-session and am trying to secure my cookies. I am able to get it working with this middleware setup:

```
app.use(require('express-session')({
  secret: 'some secret',
  resave: false,
  saveUninitialized: false
}))

app.use(csrf());
app.use(function(err, req, res, next) {
    if (err.code !== 'EBADCSRFTOKEN') return next(err);
    res.status(403).json({"error": "session has expired or tampered with"});
});
```

But if I add a cookie option to express-session, I get the session tampered error. Do you know how to use csrf with cookie options?

**Comment by dougwilson** [comment]
Hi @klunghamer sorry you're having trouble. The settings to change the cookie security would be through the `express-session` module above. The CSRF tampered error just means that the submitted token doesn't match the secret in the session (or no session was loaded).

So a couple questions for you:

1. Have you tried to clear your cookies (or just use something like Chrome Incognito mode) after you changed the cookie setting? If you already have a cookie set, changing it to be secure the browsers will just ignore the request since the attributes on the server won't match the cookie already set in the browser, so this is a good place to start.
2. What is the security setting you're trying to set in the `express-session` module? I assume it's `cookie: { secure: true }`, is that correct?
3. Is your server running over `https://` and are there any certificarte errors (like you're using a self-signed certificate)?
4. Is your Node.js server directly doing the HTTPS for secure or is the traffic going through a reverse proxy first like NGINX?

**Comment by dougwilson** [comment]
Closing due to no response.
