### ISSUE TITLE
Getting "invalid csrf token" even when the token exists in the request

### ISSUE THREAD

**Issue by movufedulo** [expressjs/csurf#173]
I see some failing calls (querying our analytics database).
All calls have a token (example value: `u0erMhlV-Kkic246hUOsSDD0mYzPPyUObUbY`) and some fail with `EBADCSRFTOKEN`.
What might be causing the failures?
Assuming the browser session never expired (in practice our sessions only expire on refresh as they last very long).

**Comment by dougwilson** [comment]
A bad token error means that the provided token doesn't match the stored secret.

**Comment by movufedulo** [comment]
What may cause that?
I mean - assuming a user GETs a page (containing a token) which allows them to POST something (sending the token back).
Can you please give me some hint to what may go wrong? It works for most cases but fails for some.

**Comment by dougwilson** [comment]
So which method are you using to store the secret: via a cookie or in a server session?

**Comment by adrianaisemberg** [comment]
(sorry I used a test user to post the original message)

Here's how I create it:
`csrf({ cookie: { key: '_csrf', httpOnly: true, secure: true } });`
I guess, a cookie... ?

**Comment by dougwilson** [comment]
Yea, that's a cookie. So there are various things that go on during the process:

(1) When a request comes in, if the cookie `_csrf` is not in the request and the token is there, you'll get `EBADCSRFTOKEN`
(2) If the user has a `_csrf` cookie already in their browser with different attributes (like maybe you served it without `httpOnly: true` before, then the browser will ignore the set
(3) Due to `secure: true` if the user's browser is over HTTP the cookie will not send (like (1) above). This could be if your site is dual HTTPS/HTTP or they are being MITM'd (could be a corp network appliance, even).

I'm sure there are many other ways to fail as well, for example maybe they had no cookie and two requests from their web browser came in simultaneously and the cookie the browser kept was not the one from the page with the token.

**Comment by adrianaisemberg** [comment]
I looked into our code and history and checked the scenarios and I don't see anything that matches any of the above 3 options.
1. A csrf token is always present in the request (I see it in our telemetry, for example: `u0erMhlV-Kkic246hUOsSDD0mYzPPyUObUbY`)
2. The browser has only one csrf cookie. For some reason it says it expires on `1969-12-31T23:59:59.000Z` but regardless it still works (except for those rare cases it doesn't).
Besides that, it is and was always http-secured.
3. All our sessions are always https.

I tried making it fail with simultaneous browser sessions but it is pretty much robust (you're doing a great job!!!). It never fails (again, except those rare cases).

Is there anything else you can suggest to help investigate the failures?
Maybe some code we can add to verify something and add some props to our analytics?

**Comment by adrianaisemberg** [comment]
Never mind. We've found something.

**Comment by adrianaisemberg** [comment]
One user-scenario was triggering setting the token to null.
Thanks for your support!

**Comment by adrianaisemberg** [comment]
Feel free to close the issue as I no longer have access to the test account which I accidentally used to create this issue.

**Comment by dougwilson** [comment]
Hi @adrianaisemberg sorry I wasn't able to reply quickly above. I'm glad you got it worked out. I'll close this issue for now, but if you're interested in sharing, I would love to hear 😆especially if perhaps we can improve the module in some way from this.
