### ISSUE TITLE
Invalid csrf Token in react app

### ISSUE THREAD

**Issue by prateeksjoshi** [expressjs/csurf#194]
in my app login is static html which is outside react app. post login is in react. 
Once i successfully login it goes inside react app. 

But whenever i am hitting login button at that time itself it throws error of invalide csrf .
I want to handle csrf in react application. I am reading csrf in meta tag.

How to do it?
Below is the screenshot of my server file
![Screen Shot 2019-08-20 at 12 55 41 PM](https://user-images.githubusercontent.com/1804126/63326456-eb58b900-c349-11e9-93a5-ea7cd851a5f2.png)

**Comment by dougwilson** [comment]
I believe, based on your description, you're saying that you are not sending the csrf token with your login since that is a static page. In order to handle that, you have to not enforce csrf token checking on that login route which the static page submits to.

Here is an example for how to make a route like your login be outside if csrf validation: https://github.com/expressjs/csurf/blob/master/README.md#ignoring-routes

If you're still having issues, please provide more explanation to your issue, how that example does not help to solve it, and your full source code so we can try to find a solution.
