### ISSUE TITLE
Isn't passing both _csrf & XSRF-TOKEN dangerous?

### ISSUE THREAD

**Issue by Uzwername** [expressjs/csurf#201]
Hello,

First of all, thank you for a great middleware that makes life so much easier.

I have a question (being a complete newbie in this topic) regarding best practices.

I have a static website generated with [Gatsby](https://www.gatsbyjs.org/), so no SSR is used, my code as for now is like follows:

```javascript
…

app.use(function (req, res, next) {
  res.cookie(`XSRF-TOKEN`, req.csrfToken());
  next();
});

app.use(express.static(path.join(__dirname, `public`)));
```

So, as you see, in order to implement csurf, I pass value returned from `req.csrfToken()` as a cookie. On the front-end my script reads this value from cookie & inserts it into the hidden field named `_csrf`.

This approach is mentioned in the documentation and in fact, it seems to be the recommended way for SPAs.

Nevertheless it seems like it's much more vulnerable to have both values stored in cookies.

Is this approach less secure than the one provided for SSR?
If it is, is there a way to reduce security risks?

**Comment by dougwilson** [comment]
I'm not aware of any security risks with it in which the cross site context is not breached. The documentation was contributed by @zelongc would would be the one to answer any specific questions on how it works.

If you do have a demonstrated way in which this method by passes the cross site protection, you're welcome to share it and we can remove it, but otherwise I'm not aware if any danger it introduces which is why it was included in the documentation, but that doesn't mean there isn't if someone can provide a demonstration.
