### ISSUE TITLE
Occasional invalid CSRF tokens when using the SPA pattern

### ISSUE THREAD

**Issue by randomdross** [expressjs/csurf#247]
I've set up csurf in a sort of "log only mode" that lets me see requests where there would be an invalid token, but not actually block those requests (yet).

I'm using the "cookie" option for csurf and setting the XSRF-TOKEN cookie as per the SPA pattern:
`res.cookie('XSRF-TOKEN', req.csrfToken());`

At the client side, outgoing PUT / POST / DELETE fetch requests take the XSRF-TOKEN cookie and place it into the x-csrf-token header.

On particular endpoints, I still see occasional invalid token reports.  In most of these cases the XSRF-TOKEN cookie actually matches the x-csrf-token header.  Presumably the mismatch is the comparison between the x-csrf-token header and the _csrf cookie.  I'm not sure what the real-world cause of this mismatch might be.  What might cause the _csrf cookie to get "out of sync" like this?

The failures that I'm seeing do seem to affect a particular set of routes, not the application as a whole.  So it's likely something about those routes or the way they are being called from the client that is causing the mismatches.

One possible hint -- in some of these cases (not all) I see the origin header set to 'null', which is a bit strange.

**Comment by dougwilson** [comment]
Hi @randomdross thanks for the report. It is hard to of course determine what the issue is without a reproduction case. Perhaps we can gather some insight into the issue if you can include the full copy of the request headers for a request that fails? Namely the `cookie` header along with your `x-csrf-token` header.

**Comment by randomdross** [comment]
Thanks @dougwilson!  I won't include the full cookie / headers right off the bat, but I can add in additional info upon request.

Here are the relevant cookies from a request that had a token mismatch:
_csrf=08Ul4K2GAU5YcPGFN2f73SXD
XSRF-TOKEN=LL89f4Wa-SjEGGOm1cEOnsWZKXbWY8sbF_HM

Header from the request:
x-csrf-token: LL89f4Wa-SjEGGOm1cEOnsWZKXbWY8sbF_HM

I'm assuming the x-csrf-token value is not a match for the _csrf cookie value, though I haven't actually done the math to confirm.

**Comment by dougwilson** [comment]
> I'm assuming the x-csrf-token value is not a match for the _csrf cookie value, though I haven't actually done the math to confirm.

Correct, as the `_csrf` cookie this module sets contains the secret and the x-csrf-token value submitted is the token. A token basically consists of a salt and the secret, meaning you have n tokens for every 1 secret. This is just for protecrion from the old BEAST attack.

Unfortunately the secret you posted does not belong to the token, which is why the validation failed. It seems likely there somewhere there is an issue where the client does not send the `_csrf` cookie to the server and the server will automatically generate a new one, which the client then is storing. But your SPA is holding on to the now mismatching token in the live javascript. I have seen this exact scenario a number of times. Solving it would be hunting for where in the app this is happening.

**Comment by randomdross** [comment]
If the server sets a new _csrf cookie, I wonder why it wouldn't also set the XSRF-TOKEN header properly in the same response.  Seems like it should.

Separate from that, I wonder if disabling the "cookie" option in csurf might help me avoid this problem altogether.

**Comment by dougwilson** [comment]
Well, this module has nothing to do with setting the XSRF-TOKEN header in a response; this module only manages the `_csrf` cookie and exposes the `req.csrfToken()` method for your own logic on how you need to expose the token for your specific front-end implementation.

**Comment by dross-seekout** [comment]
Ahh...  I actually do see some places where the code might short-circuit and send the response after setting the _csrf cookie but before setting the XSRF-TOKEN cookie.  Thanks for the tip, I'll dig into this a bit deeper!

**Comment by randomdross** [comment]
Ahh... I actually do see some places where the code might short-circuit and send the response after setting the _csrf cookie but before setting the XSRF-TOKEN cookie. Thanks for the tip, I'll dig into this a bit deeper!

**Comment by dougwilson** [comment]
No problem. I'm going to close this for now, but can re-open if you fond anything.
