### ISSUE TITLE
Does cookie csurf actually work?

### ISSUE THREAD

**Issue by deian** [expressjs/csurf#40]
Can you guys put a working example somewhere please? I can't get this to work with obvious parameters.

**Comment by dmaker3000** [comment]
Doesn't work for me either.
The token set on cookie doesnt get authorized (using axios),
and is different in value what u get in req.csrfToken().

**Comment by asafcode** [comment]
It appears that cookie mode is broken because in that mode, the token does not get tokenized.

Tokens.prototype.verify returns false because if Tokens.prototype._tokenize is never executed, '-'  is not found in the token

 look at the two functions below:

Tokens.prototype._tokenize = function tokenize (secret, salt) {
  return salt + '-' + hash(salt + '-' + secret)
}

Tokens.prototype.verify = function verify (secret, token) {
  if (!secret || typeof secret !== 'string') {
    return false
  }

  if (!token || typeof token !== 'string') {
    return false
  }

  var index = token.indexOf('-')

  if (index === -1) {
    return false
  }

  var salt = token.substr(0, index)
  var expected = this._tokenize(secret, salt)

  return compare(token, expected)
}
