### ISSUE TITLE
ignoreRoutes as extension of ignoreMethods

### ISSUE THREAD

**Issue by pszabo1** [expressjs/csurf#75]
hey there.
I'm currently making use of the csurf module and having an issue, which I think is interesting for others too and can be fixed very easy:
I do want to use and valide csurf for every method, also for get, head, options, etc. - but I want to specifiy some specific routes, which should not be validated.
My quickfix was to fork your module on my private npm and include the following:

```js
var ignoreRoutes = options.ignoreRoutes === undefined
? []
: options.ignoreRoutes;

if (!ignoreMethod[req.method] &&
ignoreRoutes.indexOf(req.path.replace(new RegExp("/", "g"), "")) === -1) {
verifytoken(req, tokens, secret, value(req));
} 
```
Now I could use the middleware that way:
```js
var csrfExcludedRoutes = ["someRoute"];

this.app.use(csrf({cookie: true, httpOnly: false, ignoreMethods: [], ignoreRoutes: csrfExcludedRoutes}));
```

I want to get the csrf-token created, but not validated. Is there another way to do that?

**Comment by billjohnston** [comment]
:+1:

**Comment by crisward** [comment]
For those of you who don't want to fork and create your own npm module, I've found you can achieve the above with code like this.

```
var csrf  = require('csurf');
var csrfIgnore =['/path/to/ignore/','/another/path/to/ignore/'];
app.use(function(req, res, next){
        if(csrfIgnore.indexOf(req.path)==-1){
          csrf({cookie:true})(req, res, next)
        }else{
          next();
        }
});
```

Hope that helps someone.

**Comment by alexbooker** [comment]
Yep. This would be awesome.

In addition to @crisward solution, you can also automatically populate the `locals` property with the token:

```javascript
var csrfIgnore = ["/login"];
app.use(function(req, res, next){
  if(csrfIgnore.indexOf(req.path)==-1){
    csrf()(req, res, next)
  }else{
    next();
  }
});

app.use(function(req, res, next) {
  if (typeof req.csrfToken === "function") {
    res.locals.csrfToken = req.csrfToken();
  }
  next();
});
```

This is really useful when you have a *logout* link on every page that you want to secure from cross-site request forgery.

**Comment by alexbooker** [comment]
I am actually just securing forms that do not need securing at the moment (i.e. ones who do not require the user to be authenticated) just because it is *much* simpler than the solution above.

**Comment by gabeio** [comment]
csrf doesn't have to be for everything the user does... logout can just be a get request why does it have to be a post? why is logging a user out so dangerous/large that it needs to be a post? I am not disagreeing that being able to ignore routes can be beneficial. but as a side note if you attach csrf after the route you need to not have csrf running on top of that works also ie:

```Javascript
app.use('/api',require('./api)); // this will not be csrf verified
app.use(csrf);
app.use('/theRest',require('./another'));
```

ignoreRoutes would be extra code for the same thing that already works.

**Comment by gabeio** [comment]
@dougwilson it might be beneficial to have an example of ignoring areas like api's on the README for this module separately from express.

**Comment by alexbooker** [comment]
I did not think about that, that is a good solution! Thanks, @gabeio.

> csrf doesn't have to be for everything the user does... logout can just be a GET request why does it have to be a POST? why is logging a user out so dangerous/large that it needs to be a POST?

There are numerous reasons why logout should use POST  and not a GET. You can read more about that [here](https://www.quora.com/Why-do-some-websites-implement-their-logout-link-as-a-form-post-via-JavaScript-versus-a-plain-old-GET-request) and [here](https://stackoverflow.com/questions/3521290/logout-get-or-post). You can also examine how secure sites implement logout - GitHub, for instance, issues a POST request with a token.

It is also important from a security stand-point *depending* on the nature of the site.

Imagine an auction site. It would be advantageous for a competing bidder to cause other bidders to be logged out. The delay between being logged out and returning to the auction page might cost the user the auction.

Another example: Imagine a website where a user can only be logged on from one location. An attacker might want to force that user to logout so that he or she can log on (there are numerous ways the attacker could log on).

**At the very *least*, this becomes an inconvenience – it becomes a usability barrier for the user.** Imagine an attacker somehow made continuous logout requests from his or her malicious page  - so long as the user has the malicious page open in a tab somewhere, every time he or she logged on to the target site, he or she would be instantaneously logged out again… This is one of tens of "attack" vectors. I am sure you can imagine more.

**Comment by dougwilson** [comment]
> @dougwilson it might be beneficial to have an example of ignoring areas like api's on the README for this module separately from express.

Can you elaborate on this or offer a PR, please :)?

**Comment by gabeio** [comment]
basically showing the code that I provided here with a guess more of an example... I will create a PR.

**Comment by dallancarr** [comment]
"CSRF should be disabled for API areas of websites where requests are all going to be fully authenticated and should be rate limited"

I think this is dangerously worded. I think "fully authenticated" needs to be explained.
