### ISSUE TITLE
CSRF token issues with Express & angular

### ISSUE THREAD

**Issue by Sunkari16** [expressjs/csurf#85]
CSURF always show 403 ("invalid CSRF token") errors , 

app.use(express.cookieParser());
app.use(csrf({
    cookie: {
        key: 'XSRF-TOKEN'
    }
}));

Versions : 
"express": "~3.4.7",
"angular": "1.3.x",

The same is explained @ http://stackoverflow.com/questions/25101804/csrf-token-issues-with-express

Below workaround helped in moving forward 
app.use(csrf());
app.use(function (req, res, next) {
    res.cookie("XSRF-TOKEN",req.csrfToken());
    return next();
});

**Comment by dougwilson** [comment]
Hi @Sunkari16 , sorry it took me a bit to get to your question, but I see you answered it yourself by closing the issue. Yes, your example at the end is what you have to do, it's not actually a "workaround", since you're not working around an issue.

It's it very common to be confused about what the "cookie" option does, and we try to explain it in our documentation at https://github.com/expressjs/csurf#cookie : that is the storage of _the token secret_, which is not the token itself, only the secret that backs it. You still have to use `req.csrfToken()` to get the token and provide that to your front-end code in some way, which is what you are doing in your example.
