### ISSUE TITLE
old tokens are useable

### ISSUE THREAD

**Issue by tsm91** [expressjs/csurf#87]
@dougwilson I  generate a new csrf token `req.csrfToken()` on each POST, PUT ajax request and send it back as response, then my next ajax request will send the new token in the header.

I recognised that it doesnt matter which csrf token i send, it will be accepted.

I am not quite familiar with csrf protection, so i thought i'd ask if this is a normal behaviour?

**Comment by gabeio** [comment]
The session holds part of the key to the acceptance. So yes any that are generated for that session are valid for the session (but should *only* work for that session).

Where the protection lies: a malicious server could always send a form to a user even including a token, but because the server can not get the session of the user (the other half of the key) the csrf will fail & block the malicious actions.

ps: make sure you are also checking that the csrf is present by including csrf() either per route or mounted prior to routes which accept post requests (which are not api for more info look at the [readme](https://github.com/expressjs/csurf#ignoring-routes))

**Comment by tsm91** [comment]
Thanks for the clarification :) So basically i dont need to re-generate the token manually.

yep i'm doing something like this:

```js
// cross site request forgery prevention (csrf)
  if (settings.csrf.enabled) {
    app.all(policies.notApiRouteRegexp, (req, res, next) => {
      csrf(settings.csrf.options)(req, res, next);
    });
  }
```

**Comment by dougwilson** [comment]
HI! You can read more about CSRF and what it does at https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29 and similar sites :) But yes, the purpose, ultimately, is to have a piece of information required in form submissions that is not part of any implicit action a web browser would make.

There are various types of CSRF ranging about how paranoid the site would like to be. The most basic level is what this module provides, and we let you generate many different tokens, even though they all work, in order to help protect against BEAST side-channel attacks, to provide something that changes per each request.
