### ISSUE TITLE
Setting 'key' attribute does not name cookie

### ISSUE THREAD

**Issue by karlbateman** [expressjs/csurf#94]
Hey all,
I have the following setup when instantiating the csurf module.

```javascript
const cookieOptions = {
  secure: false,
  httpOnly: true,
  maxAge: 3600000
}

app.use(csrf({
  key: 'authenticity_token',
  cookie: cookieOptions,
  ignoreMethods: ['GET']
}));
```

However despite setting the key attribute, the cookie is still named as `_csrf`, what am I missing?

P.S. Would be nice to see an example of using this module without cookies, or is this discouraged?

Regards,
Karl :smile:

**Comment by dougwilson** [comment]
Hi! Your configuration is not working because it doesn't match what is explained in the readme :) The `key` is an option of the cookie object, i.e. your code should be the following:
```js
const cookieOptions = {
  key: 'authenticity_token',
  secure: false,
  httpOnly: true,
  maxAge: 3600000
}

app.use(csrf({
  cookie: cookieOptions,
  ignoreMethods: ['GET']
}));
```

> P.S. Would be nice to see an example of using this module without cookies, or is this discouraged?

The reason we use `cookie: true` in all the examples is so people can actually copy and paste the examples and run them. Not using that would make it really, really hard for anyone to use. The readme should make it really clear of how to use the module without using a cookie. If not, please let us know what suggestions you would have to the readme, perhaps even as a pull request :)

**Comment by karlbateman** [comment]
Awesome, thanks for pointing that out :wink: will have a play with the session implementation and pop back with some better feedback.
