### ISSUE TITLE
How to protect GET requests?

### ISSUE THREAD

**Issue by allanesquina** [expressjs/csurf#97]
Hey guys, can you help me?
I wonder to know how can I pass the second part of token req.csrfToken() to my template to prevent GET requests? I mean, if I do not ignore the GET method, I can't access my template, so I'm not able to get the token to send it back. Split the validation from creation would solve this problem?

The code below doesn't work cos csrf already validates the token:
```javascript
// setup route middlewares
var csrfProtection = csrf({ignoreMethods: ['HEAD', 'OPTIONS']})
app.get('/', csrfProtection, function(req, res) {
  // pass the csrfToken to the view
  res.render('send', { csrfToken: req.csrfToken() })
})
```
I don't know, but I'm thinking something like that:
```javascript
// setup route middlewares
var csrfObj = csrf({ignoreMethods: ['HEAD', 'OPTIONS']})

// set the csrfToken function on req obj
app.use(csrfObj.configToken)

app.get('/', function(req, res) {
  // pass the csrfToken to the view
  res.render('send', { csrfToken: req.csrfToken() })
})

app.get('/secret', csrfObj.validate, function(req, res) {
  // pass the csrfToken to the view
  res.render('send', { csrfToken: req.csrfToken() })
})
```
I can check within error handler function like the example below, but is there a nice way to handle this?
```javascript
app.use(function (err, req, res, next) {
  if (err.code !== 'EBADCSRFTOKEN') return next(err)

  if (req.path.indexOf('/myrouter') !== -1) {
    // send the right response
    return;
  }

  res.status(403)
  res.send('form tampered with')
})
```
Thanks guys :+1:

**Comment by gabeio** [comment]
so why are you trying to protect your GET request? most of the csrf requests are blocking other websites from cross site request forgery of POST requests which are backend create/updates.

ie: a user clicks on to a bad website and clicks a "link" which actually ends up sending a email change to their account on github.com, most of the time this should be a POST request since it's a modification to the user's account, now without csrf the hacker would have just stolen the user's account. With csrf github can see that the request did not originate from github since the user's cookie & form token tell the library it's invalid.

now don't get me wrong there are reasons to NOT want user's to send GET requests from other pages... yes a "secret" page would definitely be a good example since you don't want people linking to the page you can "pretend" the page doesn't exist. Or certain database hits like a catalog that maybe you don't want the user to be able to create a "custom" version of on their website...

**Comment by allanesquina** [comment]
Hey, @gabeio, thanks for the answer. 

Ok, I got it, but I think the reason here is not relevant, I'm saying that if I can configure a method to be or not ignored, the module need to handle this option, otherwise it doesn't make sense to have this option, isn't?

**Comment by gabeio** [comment]
to be able to ignore certain verbs, which honestly can be anything, but GET is a hard one since to generate the token you need the `req.csrfToken()` which you can't get without blocking the route since (usually) it's a GET... but I believe they are working on fixing this over at #10

**Comment by allanesquina** [comment]
Cool, it will be a great feature!
Thanks @gabeio :+1:

**Comment by sundarsan** [comment]
is this feature being added to the current build ?
