### ISSUE TITLE
How to use csrf in ember app

### ISSUE THREAD

**Issue by titoesteves** [expressjs/csurf#98]
I am trying to implement csrf in my ember/express app. In my express app I have the following:

```
app.use(express.csrf());

app.use(function(req, res, next) {
  res.locals._csrf = req.session._csrf;
  return next();
});
```

in ember I have the following:

``` javascript
<div class="search-input-container">
  <input type="hidden" name="_csrf" value="{{locals._csrf}}" data="{{log '----csrfToken is----' locals._csrf}}">
  {{input action="submit" type="text" value=searchInput autofocus="autofocus" placeholder="Search for stuff..."}}
</div>
```

the log shows locals._csrf as undefined. I am using express 3.x and ember 1.x. --- Any ideas or thoughts?

**Comment by dougwilson** [comment]
From the examples (like https://github.com/expressjs/csurf#simple-express-example) you want to use `req.csrfToken()` to get the token, not `req.session._csrf`. Can you try using the following middleware?
```js
app.use(function(req, res, next) {
  res.locals._csrf = req.csrfToken();
  return next();
});
```

**Comment by titoesteves** [comment]
@dougwilson, thanks for the reply. I updated my middleware with `res.locals._csrf = req.csrfToken();`. However it is still showing as undefined.

**Comment by dougwilson** [comment]
I'm not sure how your template language is working, but maybe you should be using `{{_csrf}}` instead of `{{locals._csrf}}`?

**Comment by titoesteves** [comment]
Ember uses handlebars as its template language. I tried `{{_csrf}}` but unfortunately same issue.

**Comment by dougwilson** [comment]
So, in order for us to proceed with taking a look, please provide all the following information, as we seem to be experiencing the issue differently:

1. Version of Node.js being used.
2. Version of this module being used.
3. Complete source code needed for me to run and create an app that has this issue.
4. Complete step by step instructions for how to reproduce the issue. Be sure to include a description of how to know that the issue is occurring and what you expect the app to be doing at that stage.

Thank you!

**Comment by dougwilson** [comment]
Hi @titoesteves I hope it's OK, but I'm going to close this issue since I haven't heard back.
